on:
  workflow_dispatch:

name: Manual build
jobs:
  manual_build:
    strategy:
      matrix:
        os: [linux, darwin, windows]
    env:
      GOARCH: amd64
      GOOS: ${{ matrix.os }}
      CGO_ENABLED: 0
    name: release
    runs-on: ${{ matrix.os == 'darwin' && 'macos-latest' || 'ubuntu-latest'}}
    outputs:
      sha_linux: ${{ steps.shasum.outputs.sha_linux }}
    steps:
      - uses: actions/checkout@main
      - name: Use Go 1.20.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Test
        run: go test
        env:
          GOOS: ${{ matrix.os == 'darwin' && 'darwin' || 'linux'}}
      - name: Build ${{matrix.os}} amd64
        if: ${{ matrix.os != 'darwin' }}
        run: go build -o mob${{ matrix.os == 'windows' && '.exe' || '' }}
        env:
          GOOS: ${{ matrix.os }}
      - name: Build macOS universal
        if: ${{ matrix.os == 'darwin' }}
        run: >
          GOARCH=amd64 go build -o mob_amd64 && GOARCH=arm64 go build -o mob_arm64 && lipo -create -output mob mob_amd64 mob_arm64
        env:
          GOOS: ${{ matrix.os }}
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: ./mob${{ matrix.os == 'windows' && '.exe' || '' }}
      - name: Create release artifacts using .github/build
        run: .github/build
        env:
          VERSION: ${{ github.event.release.tag_name }}
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*{.tar.gz,_checksum.txt}"
          tag: ${{ github.event.release.tag_name }}
          file_glob: true
      - name: Set SHA
        if: matrix.os == 'darwin' || matrix.os == 'linux'
        id: shasum
        run: |
          echo "sha_${{matrix.os}}=\"$(shasum -a 256 *.tar.gz | awk '{printf $1}')\"" >> $GITHUB_OUTPUT
      - name: Set up Homebrew
        if: matrix.os == 'darwin'
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Bump homebrew formula
        if: matrix.os == 'darwin'
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW }}
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"
          brew tap ${{github.repository_owner}}/homebrew-brew
          brew bump-formula-pr -f --version=${{ github.event.release.tag_name }} --no-browse --no-audit \
          --sha256=${{ steps.shasum.outputs.sha_darwin }} \
          --url="https://github.com/${{github.repository_owner}}/mob/releases/download/${{ github.event.release.tag_name }}/mob_${{ github.event.release.tag_name }}_darwin_universal.tar.gz" \
          ${{github.repository_owner}}/homebrew-brew/mob
